all:
	# Nothing to do.

# This target sets up the source tree to run the program without installing it.
noinstall:
	# Create directory for games.
	mkdir -p ../webgames
	test -L webgames || ln -s ../webgames .
	# Create directory for deps.
	mkdir -p deps
	# Get M.grl and set it up. Use wijnen fork for now, because we use an unreleased feature.
	test -d deps/m.grl || (cd deps && git clone https://github.com/wijnen/m.grl && ${MAKE} -C m.grl)
	test -f html/gl-matrix.js || ln -s ../deps/m.grl/demos/gl-matrix.js html/
	test -f html/mgrl.js || ln -s ../deps/m.grl/mgrl.js html/
	# Get Python modules and set them up.
	test -d deps/python-fhs || (cd deps && git clone https://github.com/wijnen/python-fhs)
	test -f fhs.py || ln -s deps/python-fhs/fhs.py .
	test -d deps/python-network || (cd deps && git clone https://github.com/wijnen/python-network)
	test -f network.py || ln -s deps/python-network/network.py .
	test -d deps/python-websocketd || (cd deps && git clone https://github.com/wijnen/python-websocketd)
	test -f websocketd.py || ln -s deps/python-websocketd/websocketd.py .
	test -f html/builders.js || ln -s ../deps/python-websocketd/builders.js html/
	test -f html/rpc.js || ln -s ../deps/python-websocketd/rpc.js html/

clean:
	# Remove everything generated by noinstall, except the webgames directory in the parent directory.
	rm -rf deps
	rm -f webgames fhs.py network.py websocketd.py html/gl-matrix.js html/mgrl.js html/builders.js html/rpc.js
