#!/bin/sh

#This script only creates and updates the system files.

cd "`dirname "$0"`"

# Create javscript pot
grep -E "<title>|class='translate'" html/index.html \
	| cut -f2 -d'>' \
	| cut -f1 -d'<' \
	| sed 's/"/\\\\"/g' \
	| sed 's/&lt;/</g' \
	| sed 's/&gt;/>/g' \
	| sed 's/&amp;/\&/g' \
	| while read line ; do
		echo 'console.info(_("'"$line"'"));'
	done \
	| xgettext --add-comments -LJavaScript - html/webgame.js -o webgame-po/javascript.pot

# Create python pot
xgettext --add-comments -LPython webgame webgame_client.py -o webgame-po/python.pot

# Merge pot files
msgcat webgame-po/javascript.pot webgame-po/python.pot -o webgame-po/webgame.pot

# Update translations.
for lang in webgame-po/*.po ; do
	msgmerge --update "$lang" webgame-po/webgame.pot
done

rm webgame-po/javascript.pot webgame-po/python.pot webgame-po/webgame.pot
