#!/bin/sh

'''
Translation structure:
xx/LC_MESSAGES/<gamename>.mo <- webgame/po/xx.po, <game>/po/xx.po
xx/LC_MESSAGES/<gamename>-js.mo <- webgame/po.js/xx.po, <gamename>/po.js/xx.po

webgame/po*/xx.po is built from webgame/po*/webgame.pot
<gamename>/po*/xx.po is built from a temporary pot

po/webgame.pot <- webgame.py, webgame_client.py
po.js/webgame.pot <- html/webgame.html, html/webgame.js
<gamename>/po/temp.pot <- <gamename>/*.gpy, <gamename>/*.py, <gamename>/ai
<gamename>/po.js/temp.pot <- <gamename>/html/*.js

This script only creates and updates the system files.
'''

cd "`dirname "$0"`"

# Create po.js/webgame.pot
grep "class='translate'" html/webgame.html \
	| cut -f2 -d'>' \
	| cut -f1 -d'<' \
	| sed 's/"/\\"/g' \
	| while read line ; do
		echo 'console.info(_('"$line"'));'
	done \
	| xgettext -L=JavaScript - html/webgame.js -o po.js/webgame.pot

# Create po/webgame.pot
xgettext webgame.py webgame_client.py -o po/webgame.pot

# Update translations.
for lang in po/*.po ; do
	msgmerge --update "$lang" po/webgame.pot
for lang in po.js/*.po ; do
	msgmerge --update "$lang" po.js/webgame.pot
