#!/usr/bin/python3

'''
Compiler for webgames.  This program does the following:

- Create a directory that contains all files required for running the game.
- Inject code into html and js files to load all assets.
- Add header and footer to main file so it is an executable.
- Run the newly built server.

The result is placed in the location for webgames, $(XDG_DATA_HOME)/webgame by
default.  Under there, the game is placed named $GAMENAME, the assets are
placed in html/$GAMENAME/, and extra python files are placed under
modules/$GAMENAME/.  The generated header in the executable adds that path to
the module search path if it is created.

If modules that are used by the builder are included from the main source
directory, they are copied into the build directory.  network, websocketd and
webgame are imported so this method can be used for them.

game
modules/game/support.py
html/mgrl.js
html/gl-matrix.js
html/builders.js
html/rpc.js
html/webgame.js
html/webgame.css
html/game/main.js
html/game/index.html
html/game/img/texture.png
html/game/jta/object.jta
'''

import fhs
import network
import websocketd
import webgame
import sys
import os
import shutil
import json
import subprocess

config = fhs.init({'src': '.', 'dest': '', 'link': True, 'name': '', 'base': '', 'run': True}, game = True, packagename = 'python3-webgame')

dest = config['dest'] or fhs.write_data('webgame', dir = True, opened = False)
main = [x for x in os.listdir(config['src']) if os.path.splitext(x)[1] == os.extsep + 'gpy' and not os.path.isdir(os.path.join(config['src'], x))]
if len(main) != 1:
	sys.stderr.write('only one main file allowed; found ' + ', '.join(main) + '\n')
	sys.exit(1)
main = os.path.splitext(main[0])[0]
name = config['name'] or main.capitalize()
webbase = "\t\t<base href='{}'/>".format(config['base']) if config['base'] else ''
modules = [x for x in os.listdir(config['src']) if x.endswith(os.extsep + 'py') and not os.path.isdir(os.path.join(config['src'], x))]
jssrc = os.path.join(config['src'], 'html')
if os.path.isdir(jssrc):
	js = [x for x in os.listdir(jssrc) if x.endswith(os.extsep + 'js') and not os.path.isdir(os.path.join(jssrc, x))]
	assets = [x for x in os.listdir(jssrc) if os.path.isdir(os.path.join(jssrc, x))]
else:
	websocketd.log('Warning: no html directory found in {}; game will be useless'.format(config['src']))
	js = []
	assets = []
js.sort()
assets.sort()

if os.path.exists(os.path.join(dest, 'html', main)):
	shutil.rmtree(os.path.join(dest, 'html', main))
os.makedirs(os.path.join(dest, 'html', main))

def copy(src, dst):
	assert src and os.path.exists(src)
	src = os.path.abspath(src)
	dst = os.path.abspath(dst)
	base = os.path.dirname(dst)
	if not os.path.isdir(base):
		os.makedirs(base)
	if config['link']:
		if os.path.exists(dst):
			os.unlink(dst)
		os.symlink(src, dst, os.path.isdir(src))
	else:
		if os.path.exists(dst):
			shutil.deltree(dst)
		shutil.copytree(src, dst)

# Write or link python modules.
if len(modules) > 0:
	os.makedirs(os.path.join(dest, 'modules', main))
	for m in modules:
		copy(os.path.join(config['src'], m), os.path.join(dest, 'modules', main, m))

# Write javascript files.
for j in js:
	copy(os.path.join(jssrc, j), os.path.join(dest, 'html', main, j))

# Write or link assets.
for a in assets:
	copy(os.path.join(jssrc, a), os.path.join(dest, 'html', main, a))

# Write or link default files.
index = os.path.join(dest, 'html', main, 'index' + os.extsep + 'html')
with open(index, 'w') as f:
	files = ["\t\t<script type='application/javascript' src='{}/{}'></script>".format(main, f) for f in js]
	#print('name: {}\nbase: {}\nsource: {}'.format(name, webbase, files))
	f.write(fhs.read_data(os.path.join('html', 'webgame' + os.extsep + 'html')).read().replace('#NAME#', name).replace('#MAIN#', main).replace('#BASE#', webbase).replace('#SOURCE#', '\n'.join(files)))
copy(index, os.path.join(dest, 'html', 'index' + os.extsep + 'html'))

def makeaudio(dirobj, dir):
	if not os.path.isdir(dir):
		return []
	ret = []
	for f in os.listdir(dir):
		if os.path.splitext(f)[1][len(os.path.extsep):] not in ('wav', 'ogg', 'mp3'):
			continue
		if os.path.isdir(f):
			d = dirobj.copy()
			d.append(f)
			ret.extend(makeaudio(d, os.path.join(dir, f)))
		else:
			ret.append((dirobj, f, os.path.splitext(f)[0]))
	return ret
audio = json.dumps(makeaudio([], os.path.join(config['src'], 'html', 'audio')))

loader_js = [None, None]
for subdir, use_3d in (('2d', False), ('3d', True)):
	targets = []
	for base in ('img', 'jta', 'gani', 'audio', 'text'):
		for d in (os.path.join('html', base), os.path.join('html', subdir, base)):
			for p in fhs.read_data(d, dir = True, multiple = True, opened = False):
				targets.extend(f for f in os.listdir(p) if not f.startswith('.') and not os.path.isdir(os.path.join(p, f)))
	if len(targets) > 0:
		loader_js[use_3d] = '\n'.join("\tplease.load('{}');".format(f) for f in targets)
	else:
		# Nothing to load, but force the "finished loading" event to fire anyway.
		loader_js[use_3d] = '\twindow.dispatchEvent(new CustomEvent("mgrl_media_ready"));'

can_2d = os.path.isdir(os.path.join(config['src'], 'html', '2d'))
can_3d = not can_2d or os.path.isdir(os.path.join(config['src'], 'html', '3d'))
if can_2d and can_3d:
	use3d = '''\
	use_3d = true;
	if (document.location.search[0] == '?') {
		var s = document.location.search.substring(1).split('&');
		for (var i = i; i < s.length; ++i) {
			var kv = s[i].split('=', 1);
			if (kv[0] == '2d' && kv[1] != '0') {
				use_3d = false;
				break;
			}
		}
	}'''
elif can_2d:
	use3d = '\tuse_3d = false;'
else:
	use3d = '\tuse_3d = true;'

if can_3d:
	with open(os.path.join(dest, 'html', main, 'webgame' + os.extsep + 'js'), 'w') as f:
		f.write(fhs.read_data(os.path.join('html', 'webgame' + os.extsep + 'js')).read().replace('#LOAD#', loader_js[True]).replace('#AUDIO#', audio).replace('#USE3D#', use3d).replace('#MAIN#', main))
if can_2d:
	with open(os.path.join(dest, 'html', main, 'webgame-2d' + os.extsep + 'js'), 'w') as f:
		f.write(fhs.read_data(os.path.join('html', 'webgame' + os.extsep + 'js')).read().replace('#LOAD#', loader_js[False]).replace('#AUDIO#', audio).replace('#USE3D#', use3d).replace('#MAIN#', main))
with open(os.path.join(dest, 'html', 'rpc' + os.extsep + 'js'), 'w') as f:
	f.write(fhs.read_data('rpc' + os.extsep + 'js', packagename = 'python3-websocketd').read().replace('#WEBSOCKET#', "(window.hasOwnProperty('MozWebSocket') ? new MozWebSocket('ws://' + document.location.host + '/{}/websocket/') : new WebSocket('ws://' + document.location.host + '/{}/websocket/'))".format(main, main)))
copy(fhs.read_data(os.path.join('html', 'webgame' + os.extsep + 'css'), opened = False), os.path.join(dest, 'html', 'webgame' + os.extsep + 'css'))
copy(fhs.read_data(os.path.join('html', 'gl-matrix' + os.extsep + 'js'), opened = False), os.path.join(dest, 'html', 'gl-matrix' + os.extsep + 'js'))
copy(fhs.read_data(os.path.join('html', 'mgrl' + os.extsep + 'js'), opened = False), os.path.join(dest, 'html', 'mgrl' + os.extsep + 'js'))
copy(fhs.read_data('builders' + os.extsep + 'js', opened = False, packagename = 'python3-websocketd'), os.path.join(dest, 'html', 'builders' + os.extsep + 'js'))

# Write main file.
with open(os.path.join(dest, main), 'w') as f:
	f.write('#!/usr/bin/python3\n')
	f.write('import sys\n')
	f.write("sys.path = ['{}'] + sys.path\n".format(os.path.join(dest, 'modules')))
	if len(modules) > 0:
		f.write("sys.path = ['{}'] + sys.path\n".format(os.path.join(dest, 'modules', main)))
	f.write('import webgame\n')
	f.write(open(os.path.join(config['src'], main + os.extsep + 'gpy')).read())
	f.write('\nwebgame.Game()\n')
os.chmod(os.path.join(dest, main), 0o755)

# Copy bundled modules.
mydir = os.path.realpath(os.path.dirname(sys.argv[0]))
for m in sys.modules:
	if m == '__main__':
		continue
	if not hasattr(sys.modules[m], '__file__'):
		#print('no file: {}'.format(m))
		continue
	if os.path.realpath(os.path.dirname(sys.modules[m].__file__)) != mydir:
		#print('wrong dir: {} {}'.format(mydir, sys.modules[m].__file__))
		continue
	target = os.path.join(dest, 'modules')
	if not os.path.exists(target):
		os.mkdir(target)
	shutil.copy2(sys.modules[m].__file__, os.path.join(target, os.path.basename(sys.modules[m].__file__)))

# Run.
if config['run']:
	subprocess.Popen([os.path.join(dest, main)], close_fds = True).communicate()
